version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
  haproxy:
    image: haproxy:2.3
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
